### ISSUE TITLE
Vocab size of datasets in code not matching with values stated in the paper

### ISSUE THREAD

**Issue by thineswaran** [jbarnesspain/sota_sentiment#1]
The vocab size of datasets stated in the paper is different from the size generated while running the code.

For example, when I print the vocab size of the Sentube auto dataset in bow.py , it shows 10609 (different from 18569 as stated in page 5 of the paper).

It's the same problem for all other datasets:

Sentube tablet vocab size in code is 10904, but it's 20276 in the paper

Sst bin vocab size in code is 17540, but it's 17539 in the paper

Sst fine vocab size in code is 19501, but it's 19500 in the paper

Opener vocab size in code is 2393, but it's 2447 in the paper

Semeval vocab size in code is 21169, but it's 21163 in the paper

Is it a coding issue or is there any issue with the datasets?

**Comment by jerbarnes** [comment]
Hi @thineswaran,

It seems to be a mix of the two. For the SenTube datasets, I get 10608 (auto) and 10899 (tablet) and 2391 for OpeNER. The rest I get the same as in the paper. Just out of curiosity, where are you putting the print statement?

Thanks,

**Comment by thineswaran** [comment]
Thanks a lot for your reply, @jbarnesspain  

If you check bow.py in this repository, vocab creation happens from line 82 to line 86. I've put my print statement after that, before line 88.

**Comment by jerbarnes** [comment]
That's where I have the print statement as well. I cloned the repository again and ran it from there and I get the same. I'm using Python 3.4.3, although I'm not sure if that will make a difference for this particular issue.

**Comment by thineswaran** [comment]
I'm using Python 2.7 & my numbers are similar to yours. Guess it's more of a dataset issue, than coding issue.

Thanks for replying. Closing this issue now.
